apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  labels:
    app: react-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-deployment
  template:
    metadata:
      labels:
        app: react-deployment
    spec:
      containers:
      - name: react-deployment
        image: kubernetes-frontend-ui:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-deployment
spec:
  selector:
    app: react-deployment
  ports:
  - protocol: "TCP"
    port: 4000
    targetPort: 3000
  type: LoadBalancer