version: '3.4'

services:
  amirappareldemouireact:
    image: amirappareldemouireact
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
